"""
Django settings for saiddit project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load backend/.env. Variables already set in the environment (e.g. by
# docker compose) take precedence over the file.
load_dotenv(BASE_DIR.parent / '.env')


# In both helpers a blank value counts as unset: compose passes `${VAR:-}`
# through as an empty string, which would otherwise silently wipe out the default.

def env_bool(name, default=False):
    value = os.environ.get(name, '').strip() or str(default)
    return value.lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    value = os.environ.get(name, '').strip() or default
    return [item.strip() for item in value.split(',') if item.strip()]


# Deployment environment: 'LOCAL' or 'PROD'.
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'LOCAL').strip().upper()
if ENVIRONMENT not in ('LOCAL', 'PROD'):
    raise ValueError(f"ENVIRONMENT must be 'LOCAL' or 'PROD', got {ENVIRONMENT!r}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG')

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'corsheaders',
    'posts',
    'space',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the collected static files (e.g. the admin's CSS/JS) when DEBUG is off.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'saiddit.urls'


# CORS
# https://github.com/adamchainz/django-cors-headers

if ENVIRONMENT == 'LOCAL':
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = env_list('DJANGO_CORS_ALLOWED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True


# CSRF
# https://docs.djangoproject.com/en/6.1/ref/settings/#csrf-trusted-origins
#
# The frontend is served from a different origin than the API, and Django
# rejects an unsafe cross-origin request on its Origin header alone -- a
# perfectly valid token does not save it. Every origin the frontend is served
# from has to be listed here. CORS_ALLOW_ALL_ORIGINS has no bearing on this.

if ENVIRONMENT == 'LOCAL':
    # The Vite dev server, reachable under either spelling of loopback.
    CSRF_TRUSTED_ORIGINS = env_list(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    )
else:
    CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

CORS_ALLOW_HEADERS = (
    *default_headers,
    'accept-encoding',
    'accept-language',
    'cache-control',
    'content-length',
    'if-match',
    'if-none-match',
    'if-modified-since',
    'origin',
    'pragma',
    'x-request-id',
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saiddit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['POSTGRES_DB'],
        'USER': os.environ['POSTGRES_USER'],
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.environ['POSTGRES_HOST'],
        'PORT': os.environ['POSTGRES_PORT'],
        'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '60')),
    }
}


# Cache
# https://docs.djangoproject.com/en/6.1/topics/cache/

REDIS_URL = os.environ['REDIS_URL']

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# File storage (S3 via django-storages)
# https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'access_key': os.environ['AWS_ACCESS_KEY_ID'],
            'secret_key': os.environ['AWS_SECRET_ACCESS_KEY'],
            'bucket_name': os.environ['AWS_STORAGE_BUCKET_NAME'],
            'region_name': os.environ['AWS_S3_REGION_NAME'],
            'endpoint_url': os.environ['AWS_S3_ENDPOINT_URL'],
            # Garage serves buckets path-style (http://host:3900/<bucket>/...);
            # virtual-host style would need wildcard DNS for <bucket>.<host>.
            'addressing_style': 'path',
            'signature_version': 's3v4',
            'querystring_auth': True,
            'file_overwrite': False,
        },
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# API pagination
# List endpoints take ?page=N (1-based) and an optional ?page_size=N, and
# answer {"items": [...], "count": <total>}.

NINJA_PAGINATION_CLASS = 'ninja.pagination.PageNumberPagination'
NINJA_PAGINATION_PER_PAGE = 20
NINJA_MAX_PER_PAGE_SIZE = 100
